### ISSUE TITLE
read

### ISSUE THREAD

**Issue by yang326922943** [JunyaoHu/common_metrics_on_video_quality#11]
How can I read a mp4 file from a path, not directly generate a tensor, can you give me a implementation code

**Comment by JunyaoHu** [comment]
用opencv或者mediapy之类的都可以啊，只要最后转换成0-1之内的要求的tensor格式就行

opencv读视频就是一帧一帧读然后append在一起，mediapy就是直接读，正常的视频怎么读就怎么读，可能最多就是chw和hwc通道要换换顺序而已

**Comment by JunyaoHu** [comment]
Do you still need demo code? @yang326922943
