### ISSUE TITLE
why fvd resize img to (224, 224), Is it suitable for high-resolution?

### ISSUE THREAD

**Issue by Stick-To** [JunyaoHu/common_metrics_on_video_quality#12]
why fvd resize img to (224, 224), Is it suitable for high-resolution?

**Comment by JunyaoHu** [comment]
It is an interesting question. This is the standard for academia (probably not yet capable of producing high-resolution video at that time), we follow them, and now we may need a new metric to evaluate high-resolution videos.

**Comment by Stick-To** [comment]
ok， thanks
