### ISSUE TITLE
Target Video Dataset in FVD calculation

### ISSUE THREAD

**Issue by JCZ404** [JunyaoHu/common_metrics_on_video_quality#17]
Hi, Great work! I'm new to the video generation. May I ask which target/reference video dataset is used when we calculate the FVD metric? Is it that such a video dataset can be a subset of any real video dataset? or there is a standard dataset used for FVD calculation?

**Comment by JunyaoHu** [comment]
这个需要看你研究的什么任务。比如视频预测的话常见的数据集就是smmnist/bair/kth/cityscapes这些，同时也要follow他们的实验的帧数。
视频预测里面对于某一个数据集，抽取的都是256个样本和预测结果进行分布的比较。

This depends on what task you are studying. For example, for video prediction, the common datasets are smmnist/bair/kth/cityscapes, and also follow the number of frames in their experiments. 
In video prediction, for a certain dataset, 256 samples are extracted and compared with the distribution of prediction results.
