### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by pixeli99** [JunyaoHu/common_metrics_on_video_quality#5]
https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/dcf7e4a1d9103a19600d174f9a41a2780e40bf5d/calculate_fvd.py#L50
Should this be changed to the following code?
We need +1 ?
Because your for loop is from `0` to `numframe-1`.
```
videos_clip1 = videos1[:, :, : clip_timestamp + 1]
videos_clip2 = videos2[:, :, : clip_timestamp + 1]
```

**Comment by JunyaoHu** [comment]
Hello, you are right. **This is a serious mistake**, thank you very much for your suggestion, I will correct it later.

**Comment by JunyaoHu** [comment]
I have updated the repo.
