### ISSUE TITLE
Should images be normailzed to [-1, 1] or [0, 1]?

### ISSUE THREAD

**Issue by Lucca-cherries** [JunyaoHu/common_metrics_on_video_quality#6]
Hi, thanks for your codebase! In `calculate_lpips.py`, it says `image should be RGB, IMPORTANT: normalized to [-1,1]`. https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/calculate_lpips.py#L26C59-L26C59 However, in the README `notice` section, it says `Make sure the pixel value of videos should be in [0, 1].`https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/README.md?plain=1#L167. How to normalize to raw video whose values is in range [0, 255]? Would you please provide detailed value ranges of all the four metrics?

**Comment by JunyaoHu** [comment]
Hello, I am working for CVPR deadline, please wait for my answer.

**Comment by Lucca-cherries** [comment]
> Hello, I am working for CVPR deadline, please wait for my answer.

Same as well... Wish you good luck.

**Comment by JunyaoHu** [comment]
the inital video input range [0-1].

FVD -> [0-1] to [0-255]

https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/fvd/videogpt/fvd.py#L51-L55

SSIM -> no trans [0-1] to [0-1]

https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/calculate_ssim.py#L26-L27

LPIPS -> [0-1] to [-1-1]

https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/calculate_lpips.py#L15-L36

PSNR -> no trans  [0-1] to [0-1]

https://github.com/JunyaoHu/common_metrics_on_video_quality/blob/c12e449540cf27c1b1412c8012ecc35413fda6a7/calculate_psnr.py#L6-L8


---

How to normalize ?

if you input is [0-255]

you can

video = video/255.0

and then calculate

---

Wish you good luck too.
