### ISSUE TITLE
question about video shape and frames

### ISSUE THREAD

**Issue by AIFFFENG** [JunyaoHu/common_metrics_on_video_quality#8]
I have a question. When testing indicators, should the number of frames and the number of videos generated by the algorithm be the same as the test video?

**Comment by JunyaoHu** [comment]
Hello. 

After my personal tests, the number of frames should be the same in the computational sense (the two videos tensors are both required to do the temporal downsampling), and the number of videos can be different (the overall characteristics of the video set are considered, and the covariance is calculated)

But in fact, I haven't seen any comparison about different number of videos. If there is, please let me know. Thank you.

**Comment by AIFFFENG** [comment]
> Hello.
> 
> After my tests, the number of frames should be the same in the computational sense (the two video tensors are both required to do the temporal downsampling), and the number of videos can be different (the overall characteristics of the video set are considered, and the covariance is calculated)
> 
> But I haven't seen any comparison on different numbers of videos. If there is, please let me know. Thank you.

thanks
