### ISSUE TITLE
clip_timestamp in calculating FVD 

### ISSUE THREAD

**Issue by AIFFFENG** [JunyaoHu/common_metrics_on_video_quality#9]
"Thank you for your work, I have a question about clip_timestamp. I noticed that when calculating the FVD (Fréchet Video Distance) metric, only the first clip_timestamp frames are taken into account. Is this a reasonable approach? Does it meet the requirements of the paper? For example, if I want to test related metrics on the UCF101 dataset, how should I choose?"

**Comment by JunyaoHu** [comment]
hello

1. you mean clip_timestamp is only used for video1 not video2? here we make sure video1 and video2 have same shape, so videos should have same length. clip_timestamp will take the first 10 frames 11 frames .... len(video1) frames.

2. if you want to test on video dataset, as i known, all length should be equal. it video length is not equal, you should random sample to get a clip for each video  which has the same length.

if you have other qusetion, please reply me again

**Comment by AIFFFENG** [comment]
Thank you for your reply. 
That means if there are many videos and each video has a different length , should I need to randomly sample a continuous frame from all the videos during preprocessing? Or just take the first n frames?(n = 10 or 11 ...

**Comment by JunyaoHu** [comment]
in my project and most paper experience, you should sample a clip during preprocessing (in  your customized video dataset get_item function.

like in mcvd

https://github.com/voletiv/mcvd-pytorch/blob/master/datasets/ucf101.py#L53-L86

**Comment by AIFFFENG** [comment]
thanks

**Comment by JunyaoHu** [comment]
have a good research
